import re
import pandas as pd
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Regex patterns for WhatsApp export formats
#
# Android:  DD/MM/YYYY, HH:MM - Author: Message
# iOS:      [DD/MM/YYYY, HH:MM:SS] Author: Message
#
# Date separators vary by locale: "/" or "."
# Time separators: ":" always
# Some exports include AM/PM (12h), others use 24h
# ---------------------------------------------------------------------------

PATRONES_FECHA = [
    # Android 24h         ->  15/08/2023, 14:30 -
    r"^(\d{1,2}[\/\.]\d{1,2}[\/\.]\d{2,4}),\s(\d{1,2}:\d{2})\s-\s",
    # Android 12h EN      ->  15/08/2023, 2:30 PM -
    r"^(\d{1,2}[\/\.]\d{1,2}[\/\.]\d{2,4}),\s(\d{1,2}:\d{2}\s?[APap][Mm])\s-\s",
    # Android 12h ES      ->  11/3/2026, 8:53 p. m. -  (Spanish locale, narrow no-break space)
    "^(\d{1,2}[\\/\\.]\d{1,2}[\\/\\.]\d{2,4}),\\s(\d{1,2}:\d{2}\u202f[ap]\\.\u202fm\\.)\s-\s",
    # iOS 24h             ->  [15/08/2023, 14:30:45]
    r"^\[(\d{1,2}[\/\.]\d{1,2}[\/\.]\d{2,4}),\s(\d{1,2}:\d{2}:\d{2})\]\s",
    # iOS 12h EN          ->  [15/08/2023, 2:30:45 PM]
    r"^\[(\d{1,2}[\/\.]\d{1,2}[\/\.]\d{2,4}),\s(\d{1,2}:\d{2}:\d{2}\s?[APap][Mm])\]\s",
    # iOS 12h ES          ->  [11/3/2026, 8:53:00 p. m.]
    "^\[(\d{1,2}[\\/\\.]\d{1,2}[\\/\\.]\d{2,4}),\\s(\d{1,2}:\d{2}:\d{2}\u202f[ap]\\.\u202fm\\.)\]\s",
]

# Messages generated by WhatsApp itself (not real participants)
MENSAJES_SISTEMA = [
    "messages and calls are end-to-end encrypted",
    "los mensajes y llamadas están cifrados",
    "missed voice call",
    "llamada de voz perdida",
    "missed video call",
    "videollamada perdida",
    "you were added",
    "te añadieron",
    "changed the subject",
    "cambió el asunto",
    "changed this group",
    "changed the group",
    "security code changed",
    "el código de seguridad",
    "joined using this group",
    "you created group",
    "created group",
    "added you",
    "left",
    "salió",
    "was added",
    "fue añadido",
]

MEDIA_OMITIDA = [
    "<media omitted>",
    "<archivo adjunto omitido>",
    "image omitted",
    "video omitted",
    "audio omitted",
    "sticker omitted",
]


def _detectar_patron(linea: str) -> str | None:
    """Return the matching regex pattern for a given line, or None."""
    for patron in PATRONES_FECHA:
        if re.match(patron, linea):
            return patron
    return None


def _normalizar_hora(hora_str: str) -> str:
    """
    Normalize time strings to a format strptime can handle.
    Converts Spanish locale 'p. m.' / 'a. m.' to 'PM' / 'AM'.
    Replaces narrow no-break space (u202f) with regular space.
    """
    hora_str = hora_str.replace("\u202f", " ").strip()
    hora_str = re.sub(r"p\.?\s*m\.?", "PM", hora_str, flags=re.IGNORECASE)
    hora_str = re.sub(r"a\.?\s*m\.?", "AM", hora_str, flags=re.IGNORECASE)
    return hora_str.strip()


def _parsear_fecha(fecha_str: str, hora_str: str) -> datetime | None:
    """Try multiple date/time format combinations and return a datetime object."""
    hora_str = _normalizar_hora(hora_str)
    fecha_str = fecha_str.replace(".", "/")

    formatos = [
        "%d/%m/%Y %H:%M:%S",
        "%d/%m/%Y %H:%M",
        "%d/%m/%y %H:%M:%S",
        "%d/%m/%y %H:%M",
        "%m/%d/%Y %H:%M:%S",
        "%m/%d/%Y %H:%M",
        "%m/%d/%y %H:%M:%S",
        "%m/%d/%y %H:%M",
        "%d/%m/%Y %I:%M:%S %p",
        "%d/%m/%Y %I:%M %p",
        "%d/%m/%y %I:%M:%S %p",
        "%d/%m/%y %I:%M %p",
        "%m/%d/%Y %I:%M:%S %p",
        "%m/%d/%Y %I:%M %p",
        "%m/%d/%y %I:%M:%S %p",
        "%m/%d/%y %I:%M %p",
    ]

    combinado = f"{fecha_str} {hora_str}"
    for fmt in formatos:
        try:
            return datetime.strptime(combinado, fmt)
        except ValueError:
            continue
    return None


def _es_mensaje_sistema(contenido: str) -> bool:
    """Return True if the message was generated by WhatsApp, not a user."""
    contenido_lower = contenido.lower()
    return any(frase in contenido_lower for frase in MENSAJES_SISTEMA)


def _es_media_omitida(contenido: str) -> bool:
    """Return True if the message is a media placeholder."""
    contenido_lower = contenido.lower()
    return any(frase in contenido_lower for frase in MEDIA_OMITIDA)


def _detectar_tipo_chat(autores: list[str]) -> str:
    """Classify the chat as 'individual' (2 participants) or 'grupo' (3+)."""
    return "individual" if len(autores) <= 2 else "grupo"


def leer_archivo(ruta: str | Path) -> str:
    """Read the .txt file trying common encodings."""
    ruta = Path(ruta)
    for encoding in ["utf-8", "utf-8-sig", "latin-1", "cp1252"]:
        try:
            return ruta.read_text(encoding=encoding)
        except (UnicodeDecodeError, FileNotFoundError):
            continue
    raise ValueError(f"Could not read file: {ruta}")


def parsear_chat(ruta: str | Path) -> dict:
    """
    Parse a WhatsApp .txt export file into a structured dict.

    Returns:
        {
            "mensajes": pd.DataFrame,
            "tipo_chat": "individual" | "grupo",
            "participantes": list[str],
            "total_mensajes": int,
            "rango_fechas": (datetime, datetime),
        }
    """
    texto = leer_archivo(ruta)
    lineas = texto.splitlines()

    if not lineas:
        raise ValueError("The file is empty.")

    # Detect the format using the first valid line found
    patron_activo = None
    for linea in lineas[:50]:
        patron_activo = _detectar_patron(linea)
        if patron_activo:
            break

    if not patron_activo:
        raise ValueError(
            "Could not detect a valid WhatsApp export format. "
            "Make sure the file is a direct export from WhatsApp."
        )

    registros = []
    fecha_actual = None
    autor_actual = None
    contenido_actual = []

    def _guardar_registro():
        """Flush the current buffered message into registros."""
        if autor_actual and fecha_actual and contenido_actual:
            contenido = " ".join(contenido_actual).strip()
            if not _es_mensaje_sistema(contenido):
                registros.append(
                    {
                        "fecha": fecha_actual,
                        "autor": autor_actual,
                        "contenido": contenido,
                        "es_media": _es_media_omitida(contenido),
                        "longitud": (
                            len(contenido) if not _es_media_omitida(contenido) else 0
                        ),
                    }
                )

    for linea in lineas:
        match = re.match(patron_activo, linea)

        if match:
            # Save the previous buffered message before starting a new one
            _guardar_registro()

            fecha_str, hora_str = match.group(1), match.group(2)
            fecha_actual = _parsear_fecha(fecha_str, hora_str)

            # Everything after the timestamp prefix
            resto = linea[match.end() :]

            # Separate "Author: message content"
            if ": " in resto:
                autor_actual, contenido_inicio = resto.split(": ", 1)
                autor_actual = autor_actual.strip().lstrip("\u200e")
                contenido_actual = [contenido_inicio.strip()]
            else:
                # System message without an author — skip
                autor_actual = None
                contenido_actual = []
        else:
            # Continuation line of a multi-line message
            if autor_actual:
                contenido_actual.append(linea.strip())

    # Flush the last buffered message
    _guardar_registro()

    if not registros:
        raise ValueError("No valid messages were found after parsing.")

    df_mensajes = pd.DataFrame(registros)
    df_mensajes["fecha"] = pd.to_datetime(df_mensajes["fecha"])
    df_mensajes.sort_values("fecha", inplace=True)
    df_mensajes.reset_index(drop=True, inplace=True)

    # Derived time columns for analysis
    df_mensajes["hora"] = df_mensajes["fecha"].dt.hour
    df_mensajes["dia_semana"] = df_mensajes["fecha"].dt.day_name()
    df_mensajes["fecha_solo"] = df_mensajes["fecha"].dt.date

    participantes = sorted(df_mensajes["autor"].unique().tolist())
    tipo_chat = _detectar_tipo_chat(participantes)

    return {
        "mensajes": df_mensajes,
        "tipo_chat": tipo_chat,
        "participantes": participantes,
        "total_mensajes": len(df_mensajes),
        "rango_fechas": (df_mensajes["fecha"].min(), df_mensajes["fecha"].max()),
    }


# ---------------------------------------------------------------------------
# Quick sanity check — run directly with:  python parser.py <path_to_file>
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python parser.py <path_to_chat.txt>")
        sys.exit(1)

    # Join all arguments to support filenames with spaces
    ruta_archivo = " ".join(sys.argv[1:])
    resultado = parsear_chat(ruta_archivo)

    print(f"Chat type      : {resultado['tipo_chat']}")
    print(f"Participants   : {resultado['participantes']}")
    print(f"Total messages : {resultado['total_mensajes']}")
    print(
        f"Date range     : {resultado['rango_fechas'][0]} -> {resultado['rango_fechas'][1]}"
    )
    print()
    print(resultado["mensajes"].head(10).to_string())
    print(
        repr(
            open(
                "Chat de WhatsApp con Platica general.txt", encoding="utf-8"
            ).readlines()[4]
        )
    )
